### PR TITLE
Improve integration of localpca in DIPY

### PR DESCRIPTION
**Pull request by skoudoro**
Hi @15thai,

I just rebase and improve the implementation of your code. feel free to merge it in your branch to update it

### CODE REVIEW

**Comment by skoudoro** [comment]
It seems that you will have to rebase your branch before merging this PR. We can have an online meeting if you need help. just let me know

**Comment by 15thai** [comment]
can I make a phone call with you tomorrow? That's would be good.

**Comment by skoudoro** [comment]
yes, no problem! What time? I will send you a Zoom link on your email. It would be good after 2pm

**Comment by 15thai** [comment]
> yes, no problem! What time? I will send you a Zoom link on your email. It would be good after 2pm
@skoudoro 
2:30 will be good.Thanks

**Pull request merged**
